Copy files from old repository
ostis-apps/ostis-chemistry pull request #1
Opened 2020-03-18 09:38 UTC by Sabbaken

2020-03-18 09:41 UTC, ShunkevichDV requested changes
1. TODO вынести из файлов в Issues
2. Структуру директорий сделать не по фамилиям авторов, а по сути хранящихся файлов

2020-03-18 11:44 UTC, KovalM commented
Расширения интерфейса не работают. Необходимо:
1. Поместить из в папку interface/sc-web-extensions
2. Обновить скрипт scripts/install_ostis.sh для связки расширений интерфейса с sc-web

Если нужна будет помощь - обращайтесь.

2020-03-19 15:57 UTC, Sabbaken commented
> 1. TODO вынести из файлов в Issues
Можно не выносить это в Issues, т.к. они не для этого предназначены, а в projects
![image](https://user-images.githubusercontent.com/39835504/77086898-70f13400-6a13-11ea-9d92-bd4feef89574.png)
https://github.com/ostis-apps/ostis-chemistry/projects

2020-03-20 10:10 UTC, ShunkevichDV commented
> 
> 
> Можно не выносить todo в Issues, т.к. они не для этого предназначены, а в projects
> ![image](https://user-images.githubusercontent.com/39835504/77086898-70f13400-6a13-11ea-9d92-bd4feef89574.png)
> https://github.com/ostis-apps/ostis-chemistry/projects
> @ShunkevichDV

Хорошо, можно в Projects, перенесите тогда туда

2020-03-31 07:27 UTC, KovalM commented
> Расширения интерфейса не работают. Необходимо:
> 
> 1. Поместить из в папку interface/sc-web-extensions
> 2. Обновить скрипт scripts/install_ostis.sh для связки расширений интерфейса с sc-web
> 
> Если нужна будет помощь - обращайтесь.

Создам для этого отдельное issue.

2020-03-31 07:28 UTC, merged