Course work - Verenich
ostis-apps/ostis-chemistry pull request #4
Opened 2020-05-12 12:11 UTC by Sabbaken

2020-05-21 14:56 UTC, NikiforovSergei requested changes

2020-05-21 14:56 UTC, NikiforovSergei commented on kb/concepts/processes/nrel_chlorinezation.scs
> +binary_relation => nrel_inclusion: antireflexive_relation;;
Здесь и далее: прописывать эти включения не нужно, т. к. дуги не склеятся, будет дублирование. Да и в ims уже есть разбиение бинарного отношения.

2020-05-29 07:57 UTC, NikiforovSergei commented on kb/concepts/processes/nrel_brominezation.scs
> +sc_node_not_relation->arity;;
Прошу прощения, что не сказал сразу, в первый раз не заметил. Аналогичная ситуация, дублирование здесь и ниже.

2020-06-01 07:46 UTC, NikiforovSergei commented on kb/concepts/processes/nrel_brominezation.scs
> +nrel_brominezation<-sc_node_norole_relation;;
Вместе с дублирующейся арностью, про которую писалось в прошлый раз, были удалены и домены отношений. В удалении доменов необходимости не было.

2020-06-01 12:49 UTC, NikiforovSergei commented on kb/concepts/processes/nrel_brominezation.scs
> +sc_node_not_relation->arity;;
Похоже, что возникло стойкое недопонимание. Попробую переформулировать. Строки:
"sc_node_not_relation->arity;;
sc_node_not_relation->arity_2;;
arity_2=>nrel_measurement:2;;
...
arity_2<-arity;;
number->2;;", повторяющиеся в каждом файле приведут к тому, что это продублируется и в базе. Например, от arity будет идти несколько дуг принадлежности к arity_2. По этой причине их нужно убрать, что и было сделано, верно. Оставить нужно только одну строку, указывающую на принадлежность отношения ко множеству отношений с арностью 2. Проблема в том, что вместе с ними были удалены строки:
"nrel_iodization => nrel_first_domain: chemical_substance;;
nrel_iodization => nrel_second_domain: chemical_substance;;", описывающие домены отношения, их удалять необходимости не было. В последнем же изменении возвращена арность со всеми дублирования, но не домены.

2020-06-02 07:05 UTC, NikiforovSergei approved these changes

2020-06-02 10:47 UTC, MikhailSadovsky approved these changes

2020-06-02 10:47 UTC, merged